name: build
on: [push]

env:
    VERSION_PREFIX: "0.0.3"

jobs:
    build:
        runs-on: windows-latest

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - name: Setup .NET Core 3.1.x
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: 3.1.x
                
          - name: Setup .NET 5.0.x
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: 5.0.x

          - name: dotnet tool restore
            run: dotnet tool restore

          - name: Generate version properties
            run: dotnet ci-version-properties --output VersionInfo.props && cat VersionInfo.props

          - name: dotnet restore
            run: dotnet restore

          - name: dotnet build
            run: dotnet build --configuration Release

          - name: dotnet pack
            run: dotnet pack --configuration Release --no-build

          - name: Copy *.nuget to dist/
            run: mkdir dist/ && cp src/DotnetDynamoDBLock/bin/Release/*.nupkg dist/

          - name: Archive dist/
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist/
